version: '3.3'

services:
	wordpress:
		image: wordpress:latest
		container_name: portfolio-lp
		depends_on:
			- db
		ports:
			- "8000:80"
		environment:
			WORDPRESS_DB_HOST: db:3306
			WORDPRESS_DB_USER: wordpress
			WORDPRESS_DB_PASSWORD: wordpress
			WORDPRESS_DB_NAME: wordpress
		volumes:
			- ./wordpress:/var/www/html

	db:
		image: mysql:5.7
		container_name: portfolio-lp_mysql
		ports:
			- "4306:3306"
		volumes:
			- db_data:/var/lib/mysql
		environment:
			MYSQL_ROOT_PASSWORD: root
			MYSQL_DATABASE: wordpress
			MYSQL_USER: wordpress
			MYSQL_PASSWORD: wordpress
			
volumes:
		db_data: